name: Deploy Translate Glue

on:
  push:
    branches: [ main ]
    paths:
      - 'translate-glue/**'
  workflow_dispatch: # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /opt/translate-glue
          chmod +x update-from-github.sh
          ./update-from-github.sh
          
    - name: Test Deployment
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Wait for service to start
          sleep 10
          
          # Test health endpoint
          if curl -f -s http://localhost:3001/health; then
            echo "✅ Deployment successful - health check passed"
          else
            echo "❌ Deployment failed - health check failed"
            exit 1
          fi
